### ISSUE TITLE
Example code fails at servers = master.get_servers

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#125]
On the usage page on the website, it says to query master servers in ruby:

master = MasterServer.new(_MasterServer::GOLDSRC_MASTER_SERVER)
servers = master.get_servers
server = GoldSrcServer.new(_servers.choice)

However...

``` bash
$ gem install steam-condenser
3 gems installed
$ irb
```

``` ruby

>require 'steam-condenser'
=>true
>master = MasterServer.new(*MasterServer::GOLDSRC_MASTER_SERVER)
=>#<MasterServer:0x007fd6ba106d80 @host_names=["69.28.151.162"], @ip_addresses=["69.28.151.162"], @ip_index=0, @port=27010, @ip_address="69.28.151.162", @socket=#<MasterServerSocket:0x007fd6ba106c18 @socket=#<UDPSocket:fd 3>>> 
servers = master.get_servers
NoMethodError: undefined method `get_servers' for #<MasterServer:0x007fd6ba106d80>
    from (irb):3
    from /Users/auto/.rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in `<main>'
> servers = master.servers
SteamCondenser::TimeoutError: The operation timed out.
```

**Comment by koraktor** [comment]
Thanks for the hint on the website bug.

The timeout seems to indicate that the GoldSrc master server makes trouble once again. I'll have a look.

**Comment by ghost** [comment]
in the same example, it will also fail at
server = GoldSrcServer.new(*servers.choice)
choice is undefined as well.

**Comment by koraktor** [comment]
Well, `#choice` is a standard Ruby method for `Array`s. It exists since 1.8.7, so you should either update or use something like this:

``` ruby
server = GoldSrcServer.new(*servers[rand server.count])
```

I won't update the example for that though. Ruby 1.8.6 is really outdated now.

**Comment by ghost** [comment]
My bad. Choice was renamed (and not aliased) to sample in Ruby > 1.8.7.

**Comment by koraktor** [comment]
Oh, that's a bit different story than, maybe I'll change it so it works on 1.9, 1.8.7 _and_ 1.8.6.

**Comment by koraktor** [comment]
Sorry, I can't do anything about the master server problems, I think.

I'll have a look at it though and ask on the HLDS list.
