### ISSUE TITLE
Java 1.3.9 ERROR

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#271]
A am using Java 1.3.9 + NetBeans IDE 8.0.2
Code:
                GoldSrcServer temp_server = new GoldSrcServer("91.211.116.28", 27015);
                temp_server.initialize();
                info.setText(temp_server.getServerInfo().get("serverName").toString());
But I get error below.
All works well on version 1.3.7.jar

PLEASE HELP ME

run:
мая 15, 2015 10:28:00 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2S_INFO_Packet"
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/commons/lang3/ArrayUtils
    at com.github.koraktor.steamcondenser.PacketBuffer.getString(PacketBuffer.java:99)
    at com.github.koraktor.steamcondenser.steam.packets.S2A_INFO_DETAILED_Packet.<init>(S2A_INFO_DETAILED_Packet.java:32)
    at com.github.koraktor.steamcondenser.steam.packets.SteamPacketFactory.getPacketFromData(SteamPacketFactory.java:51)
    at com.github.koraktor.steamcondenser.steam.sockets.SteamSocket.getPacketFromData(SteamSocket.java:78)
    at com.github.koraktor.steamcondenser.steam.sockets.GoldSrcSocket.getReply(GoldSrcSocket.java:117)
    at com.github.koraktor.steamcondenser.steam.servers.GameServer.getReply(GameServer.java:270)
    at com.github.koraktor.steamcondenser.steam.servers.GameServer.updatePing(GameServer.java:489)
    at com.github.koraktor.steamcondenser.steam.servers.GameServer.initialize(GameServer.java:363)
    at serverbrowser.ServerBrowser.jButton1ActionPerformed(ServerBrowser.java:376)
    at serverbrowser.ServerBrowser.access$300(ServerBrowser.java:29)
    at serverbrowser.ServerBrowser$4.actionPerformed(ServerBrowser.java:188)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.ArrayUtils
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 47 more
мая 15, 2015 10:28:00 PM com.github.koraktor.steamcondenser.steam.sockets.QuerySocket send
INFO: Sending data packet of type "A2S_INFO_Packet"
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/commons/lang3/ArrayUtils
    at com.github.koraktor.steamcondenser.PacketBuffer.getString(PacketBuffer.java:99)
    at com.github.koraktor.steamcondenser.steam.packets.S2A_INFO_DETAILED_Packet.<init>(S2A_INFO_DETAILED_Packet.java:32)
    at com.github.koraktor.steamcondenser.steam.packets.SteamPacketFactory.getPacketFromData(SteamPacketFactory.java:51)
    at com.github.koraktor.steamcondenser.steam.sockets.SteamSocket.getPacketFromData(SteamSocket.java:78)
    at com.github.koraktor.steamcondenser.steam.sockets.GoldSrcSocket.getReply(GoldSrcSocket.java:117)
    at com.github.koraktor.steamcondenser.steam.servers.GameServer.getReply(GameServer.java:270)
    at com.github.koraktor.steamcondenser.steam.servers.GameServer.updatePing(GameServer.java:489)
    at com.github.koraktor.steamcondenser.steam.servers.GameServer.initialize(GameServer.java:363)
    at serverbrowser.ServerBrowser.jButton1ActionPerformed(ServerBrowser.java:376)
    at serverbrowser.ServerBrowser.access$300(ServerBrowser.java:29)
    at serverbrowser.ServerBrowser$4.actionPerformed(ServerBrowser.java:188)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by koraktor** [comment]
You’re missing dependencies. Either use Maven (or similar) or have a look at the [pom.xml](https://github.com/koraktor/steam-condenser-java/blob/1.3.9/pom.xml#L107-158) to see what’s needed.

**Comment by ghost** [comment]
After using Maven i have encoding problems if there is a Cyrillic character.
http://s020.radikal.ru/i720/1505/19/9134cd6acf38.png
